### ISSUE TITLE
community dashboard

### ISSUE THREAD

**Issue by parispittman** [kubernetes/contributor-site#295]
https://github.com/cncf/devstats/issues/229

moving from devstats as this might be the better place for it anyway. 

Display community facts and quantitative information. 

-twitter stats for https://github.com/kubernetesio (impressions, shares, etc)
-slack stats (messages sent, # of channels, etc)
-meetup stats (# of meetups, # of members, etc - this is on the website too)
-YouTube playlists - how many, link to last meeting on the list
-current release and other release stats
-chairs and tech leads stats (changes to sigs.yaml in the community repo: how many new chairs/tls this year, avg tenure, etc)
-github - number of repos in the org

TODO
where on the site?
break down the needs of each one / if it has an api / how we get keys to it

**Comment by SuperAayush** [comment]
Hey @parispittman I wanna work on this issue can you help me out?

**Comment by parispittman** [comment]
@SuperAayush - for sure, come to #sig-contribex on slack 

we might be able to use this 
https://github.com/cncf/landscape-graph#how-can-a-graph-help-us

**Comment by halcyondude** [comment]
Yes!  How can I engage?  I've created this so that it could be (specifically) a community dashboard.  Here's a few things of note happening in the project in the last week :)

On hosting logistics:

- (in progress) https://github.com/cncf/landscape-graph/issues/40#issuecomment-1111662444

On prior art
- https://github.com/cncf/landscape-graph/issues/5
  - https://github.com/community-graph
  - https://github.com/community-graph/dashboard (useful bits)

On design targeted to enable community engagement
- (in progress) --> https://github.com/cncf/landscape-graph/issues/54
- (next) https://github.com/orgs/cncf/projects/7/views/2

**Comment by AvineshTripathi** [comment]
Hey @halcyondude i have tried looking for docs to try this locally unfortunately I couldn't find one can you help me with this

**Comment by halcyondude** [comment]
Yes certainly, this is still very early days :)

If you want to experiment today, start here --> https://github.com/cncf/landscape-graph/blob/main/apps/local-docker/local-docker-neo.sh

**Comment by imnmo** [comment]
@halcyondude is there any update?
