### ISSUE TITLE
Error on Kubernetes Contributor Course

### ISSUE THREAD

**Issue by Sakh1l** [kubernetes/contributor-site#385]
On Section 1 of Contributor Course, page 9, about how K8s community organized it states four group but shows only three.
I believe details about User Group is missing. 
![image](https://user-images.githubusercontent.com/59551125/226183066-9a2e1b4f-af17-4127-80b8-36262d9b6c66.png)

**Comment by mrbobbytables** [comment]
Thanks, it was intentional^^;;

User groups are slated to be removed as a form of kubernetes groups - we opted to removed it from the course while we were working on it as it'd be one less thing for us to update when they are officially removed.


/close

**Comment by sftim** [comment]
I'd accept a PR to change the “four” to “three”, FWIW. However, please note our policy on [trivial edits](https://www.kubernetes.dev/docs/guide/pull-requests/#trivial-edits). Usually, bigger updates than one word are the right thing to do.

I'd make an exception here because readers will look for the missing 4th item.
